name = "petstudio"
compatibility_date = "2024-05-01"
main = "cors-proxy.js"

[observability.logs]
enabled = true  # This enables Worker logs (helpful for debugging)

[vars]
CLOUDINARY_BASE = "https://res.cloudinary.com/dh7d6otgu"

[triggers]
routes = [
  "petstudio.DI.workers.dev/proxy/*",  # Your direct worker URL
  "drkimogad.github.io/proxy/*"        # GitHub Pages route
]

